name: Go package

on: [push]

jobs:
  build:

    name: Building package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ 'mxro.de/gcp-serverless-http-example', 'mxro.de/gcp-serverless-http-example-v2' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: Build package
        run: |
          go build ${{ matrix.package }}

      - name: Run tests 
        run: |
          go test ${{ matrix.package }}